# Generated by Django 3.1.3 on 2021-01-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadexpense',
            name='misc',
            field=models.TextField(blank=True),
        ),
    ]
