# Generated by Django 3.1.3 on 2021-01-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='dr_cr',
            field=models.CharField(max_length=10),
        ),
    ]
