# Generated by Django 3.1.3 on 2021-01-23 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_auto_20210123_1358'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ledger',
            table='led',
        ),
    ]
