# Generated by Django 3.1.3 on 2021-01-24 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_auto_20210123_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='collect_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.collected_by', verbose_name='Collected By'),
        ),
    ]
