# Generated by Django 3.1.3 on 2021-01-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_auto_20210118_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='dr_cr',
            field=models.CharField(default='abc', max_length=2, verbose_name='Dr/Cr'),
        ),
    ]
