# Generated by Django 3.1.3 on 2021-01-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_auto_20210118_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandnew',
            name='dr_cr',
        ),
        migrations.AlterField(
            model_name='ledger',
            name='dr_cr',
            field=models.CharField(default='ab', max_length=2, verbose_name='Dr'),
        ),
    ]
