# Generated by Django 3.1.3 on 2021-02-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_auto_20210213_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='isChequeCleared',
            field=models.NullBooleanField(editable=False),
        ),
    ]
