# Generated by Django 3.1.3 on 2021-01-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_auto_20210118_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='dr_cr',
            field=models.CharField(default='ab', editable=False, max_length=2, verbose_name='Dr'),
        ),
    ]
