# Generated by Django 3.1.3 on 2021-02-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_ledger_ischequecleared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='isChequeCleared',
            field=models.BooleanField(blank=True, editable=False, null=True),
        ),
    ]
