# Generated by Django 3.1.3 on 2021-02-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_auto_20210213_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='isChequeCleared',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
